version: '3'
services:
  mysql:
    image: mysql:5.6.27
    ports: 
      - "127.0.0.1:3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./inintdb:/docker-entrypoint-initdb.d
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: itsme@007@
      TZ: Asis/Dhaka
volumes:
  mysqldata:
    driver: local